node {
    // Load the file 'externalMethod.groovy' from the current directory, into a variable called "externalMethod".
    def standardPipeline = load("standardPipeline.groovy")

    // Call the method we defined in externalMethod.
    standardPipeline.lookAtThis("Steve")

    // Now load 'externalCall.groovy'.
    def externalCall = load("externalCall.groovy")

    // We can just run it with "externalCall(...)" since it has a call method.
    externalCall("Steve")
}
